version: '3.1'

services:
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
    ports:
      - "3307:3306"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d/
